#!/bin/bash

set -x
set -e

if command -v wormhole >/dev/null ; then
    ## wormhole available in dom0 (Qubes R4.1)
    wormhole send --code-length=4 "$1"
    exit
fi

## wormhole not available in dom0 (Qubes R4.0)

qvm-run \
    --verbose \
    --autostart \
    --dispvm whonix-ws-15-dvm \
    --pass-io \
    -- \
    'set -eu
mkdir /tmp/qubes-remote-support
cat > /tmp/qubes-remote-support/remote-support-keys.tar.gz
exec wormhole send --code-length=4 /tmp/qubes-remote-support/remote-support-keys.tar.gz
' < "$1"
