#!/bin/bash

set -x
set -e

## TODO: do not hardcode sys-whonix - make that an environment variable or command line parameter

no_root_check() {
    if [ "$(id -u)" = "0" ]; then
        echo "ERROR: Do not run $0 as root / with sudo!"
        exit 100
    fi
}

dom0_rpc_policy_setup() {
    local append_string

    if ! test -f /etc/qubes-rpc/policy/qubes.ConnectTCP ; then
        return 0
    fi

    ## TODO: remove string
    append_string="sys-whonix dom0 allow,target=dom0"

    ## Debugging.
    cat /etc/qubes-rpc/policy/qubes.ConnectTCP
}

start_vm() {
    local qvm_ls_output

    qvm_ls_output="$(qvm-ls sys-whonix --fields state --no-spinner --raw-data)"

    if [ "$qvm_ls_output" = "Running" ]; then
        true "INFO: already running, ok."
    else
        ## Would exit non-zero if already running.
        qvm-start sys-whonix
    fi
}

vm_setup() {
    ## --pass-io is optional but useful for gathering debug output.

    qvm-run --user root --pass-io sys-whonix "systemctl stop qubes-whonix-remote-support.service"

    qvm-run --user root --pass-io sys-whonix "rm --force --verbose /usr/local/etc/torrc.d/43_remote_support_hs_autogen.conf"
    qvm-run --user root --pass-io sys-whonix "rm --force --recursive --verbose /var/lib/tor_autogen/remote_support"

    ## Check if Tor is running.
    if qvm-run --user root --pass-io sys-whonix "systemctl --no-pager --no-block status tor@default.service" ; then
        ## Yes, Tor is running. Restart it to make Tor forget the onion v3 service.
        qvm-run --user root --pass-io sys-whonix "systemctl restart tor@default.service"
    fi
}

dom0_sshd_setup() {
    mkdir -p ~/.ssh
    sudo chmod 700 ~/.ssh
    touch ~/.ssh/authorized_keys
    sudo chmod 600 ~/.ssh/*

    ## TODO: Should remove all keys from file ~/.ssh/authorized_keys that contain
    ## comment qubes-remote-support-receiver-auto-generated or delete whole file
    ## ~/.ssh/authorized_keys ?
    ##
    ## Deleting whole file ~/.ssh/authorized_keys seems more robust at the expense
    ## of advanced users and developers using custom (not by qubes-remote-support
    ## package) SSH servers.
    ## Alternativly, keys matching the SSH key comment
    ## "qubes-remote-support-receiver-auto-generated" could be removed too but
    ## that code is more fragile to race conditions.

    ## TODO: handle ~/.ssh/authorized_keys as per above

    sudo systemctl stop sshd.service
}

dom0_x2go_setup() {
    sudo systemctl stop x2gocleansessions.service
}

no_root_check
dom0_rpc_policy_setup

dom0_sshd_setup
dom0_x2go_setup

start_vm
vm_setup

true "INFO: Success."
